include: package:flame_lint/analysis_options.yaml

analyzer:
  errors:
    avoid_bool_literals_in_conditional_expressions: ignore
    avoid_catches_without_on_clauses: ignore
    avoid_positional_boolean_parameters: ignore
    comment_references: ignore
    lines_longer_than_80_chars: ignore
    type_literal_in_constant_pattern: ignore
    use_if_null_to_convert_nulls_to_bools: ignore
    use_setters_to_change_properties: ignore
    sort_pub_dependencies: ignore
  exclude:
    - 'example/**'