name: Publish plugin

on:
  workflow_dispatch:
  # release:
  #   types: [published]

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Intall dart
        uses: dart-lang/setup-dart@v1
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - name: Copy credentials
        run: |
         mkdir -p ~/Library/Application\ Support/dart
         cat <<EOF > ~/Library/Application\ Support/dart/pub-credentials.json
         ${{ secrets.CREDENTIAL_JSON }}
         EOF
         mkdir -p ~/.pub-cache
         ln -s ~/Library/Application\ Support/dart/pub-credentials.json credentials.json
      - name: Publishing
        run: flutter pub publish -f